import Animatetext from '@/component/AnimatedText/AnimatedText';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';
import React from 'react';
import AboutusContainer from './_Component/AboutusContainer';
import Ourmission from './_Component/Ourmission';
import ContactContainer from '../contact/_Component/ContactContainer';
import OurLeadership from './_Component/OurLeadership';
import WhatSetsUsApart from './_Component/WhatSetsApart';
export async function generateMetadata() {
  return {
    title: 'About',
    description: 'Generated by create next app',
  };
}
function page() {
  return (
    <div className="">
      <ResponsiveContainer className={' md:!mt-[115px] !mt-20'}>
        <div className="flex-center min-h-[60vh] !w-full md:!p-10">
          <div className="!space-y-5">
            <Animatetext x={-20} duration={1}>
              <h3 className="text-lg text-primary text-center font-semibold uppercase">About</h3>
            </Animatetext>
            <Animatetext x={20} duration={1}>
              <h3 className="md:text-5xl text-3xl text-center font-semibold">Our Company</h3>
            </Animatetext>
            <Animatetext x={-20} duration={1}>
              <h3 className="  text-center md:text-lg text-sm text-gray-700 ">
                We are a specialized database consulting firm dedicated to helping organizations
                modernize their data infrastructure through strategic cloud migrations and
                performance optimization. With deep expertise in both traditional on-premises
                database platforms and cutting-edge cloud-native solutions, we guide businesses
                through the complexities of migrating their databases to the cloud.
              </h3>
            </Animatetext>
          </div>
          <AboutusContainer />
        </div>
      </ResponsiveContainer>

      <Ourmission />
      <ResponsiveContainer>
        <div>
          <OurLeadership />
        </div>
      </ResponsiveContainer>
      <div className='!bg-[url("/images/sectionBg.png")] bg-cover bg-center bg-no-repeat'>
        <WhatSetsUsApart />
      </div>
      <ContactContainer />
    </div>
  );
}

export default page;
