import Animatetext from '@/component/AnimatedText/AnimatedText';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';
import React from 'react';
import AllServices from './_Component/AllServices';

export async function generateMetadata() {
  return {
    title: 'Service',
    description: 'Generated by create next app',
  };
}
function page() {
  return (
    <div className="">
      <ResponsiveContainer className={' md:!mt-[115px] !mt-20'}>
        <div className="flex-center min-h-[60vh] !w-full md:!p-10">
          <div className="!space-y-5">
            <Animatetext x={-20} duration={1}>
              <h3 className="md:text-lg text-primary text-center font-semibold uppercase">
                Service
              </h3>
            </Animatetext>
            <Animatetext x={20} duration={1}>
              <h3 className="md:text-5xl text-3xl text-center font-semibold">Our Services</h3>
            </Animatetext>
            <Animatetext x={-20} duration={1}>
              <h3 className="  md:text-center text-sm md:text-lg text-gray-700 ">
                We offer a wide range of services to meet your needs in the digital field. Our team
                of skilled professionals is dedicated to delivering high-quality services that meet
                your specific needs.
              </h3>
            </Animatetext>
          </div>

          {/* all services */}
          <AllServices />
        </div>
      </ResponsiveContainer>
    </div>
  );
}

export default page;
