import React from 'react';
import BookService from './Component/BookService';
import ResponsiveContainer from '@/component/ResponsiveContainer/ResponsiveContainer';

export async function generateMetadata() {
  return {
    title: 'About',
    description: 'Generated by create next app',
  };
}

function page() {
  return (
    <div>
      <ResponsiveContainer className={' md:!mt-[115px] !mt-20'}>
        <BookService />
      </ResponsiveContainer>
    </div>
  );
}

export default page;
